# config.yml
paths:
  data_dir: "./data"
  output_dir: "./output"
  database_file: "./output/database.sqlite"
  merged_file: "./output/merged.csv"

files:
  energy: "energy.csv"
  world_population: "world_population.csv"
  emissions: "emissions.csv"
  pib: "pib.xlsx"